import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kyle
 */

/**
 * picture of yu-gi-oh card backing taken from 
 * https://vignette.wikia.nocookie.net/yugioh/images/e/ee/Back-ZX-Site.png/revision/latest?cb=20130902115200
 * 
 * @author kyle
 */

public class YuGiOhBoard extends javax.swing.JFrame {

    /**
     * Creates new form yugiohBoard
     */
    public YuGiOhBoard() throws IOException {
        this.cardBack = ImageIO.read(getClass().getResource("Back-zx-site.png"));
        initComponents();
    }
    final private int HIGH_LP=8000;
    final private int LOW_LP=4000;
    
    private int[] p1BCounters=new int[10],p2BCounters=new int[10],p1RCounters=new int[10],p2RCounters=new int[10];
    private Image cardBack;
    private int whichLP=1,temp; 
    private String prevLPVal;
    private ArrayList<JTextField> lifePoints= new ArrayList<JTextField>(); 
    //this array keeps track of which button for LP editing is selected 
    //1, and 2 are add and subtract for P1. 2, and 3 are the same but for player 2
    private boolean[] lPMods = new boolean[4];
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p1Deck = new javax.swing.JButton();
        p1Spell1 = new javax.swing.JButton();
        p1Spell2 = new javax.swing.JButton();
        p1Spell3 = new javax.swing.JButton();
        p1Spell4 = new javax.swing.JButton();
        p1Spell5 = new javax.swing.JButton();
        p1Extra = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        p2LP = new javax.swing.JTextField();
        p1Graveyard = new javax.swing.JButton();
        p1Monster1 = new javax.swing.JButton();
        p1Monster2 = new javax.swing.JButton();
        p1Monster3 = new javax.swing.JButton();
        p1Monster4 = new javax.swing.JButton();
        p1Monster5 = new javax.swing.JButton();
        p1FieldSpell = new javax.swing.JButton();
        p1BCounter1 = new javax.swing.JButton();
        p1LP = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        p2Graveyard = new javax.swing.JButton();
        p2FieldSpell = new javax.swing.JButton();
        p1Monster6 = new javax.swing.JButton();
        p1Monster7 = new javax.swing.JButton();
        p1Monster8 = new javax.swing.JButton();
        p1Monster9 = new javax.swing.JButton();
        p1Monster10 = new javax.swing.JButton();
        p2Extra = new javax.swing.JButton();
        p1Spell6 = new javax.swing.JButton();
        p1Spell7 = new javax.swing.JButton();
        p1Spell8 = new javax.swing.JButton();
        p1Spell9 = new javax.swing.JButton();
        p1Spell10 = new javax.swing.JButton();
        p2Deck = new javax.swing.JButton();
        p1LPa = new javax.swing.JButton();
        p1LPs = new javax.swing.JButton();
        p2LPa = new javax.swing.JButton();
        p2LPs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        p1Deck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N
        p1Spell1.setBorderPainted(false);

        p1Spell2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Extra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p2LP.setEditable(false);
        p2LP.setForeground(new java.awt.Color(255, 0, 0));
        p2LP.setText("4000");
        lifePoints.add(p2LP);
        p2LP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p2LPKeyPressed(evt);
            }
        });

        p1Graveyard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N
        p1Monster1.setBorderPainted(false);

        p1Monster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1FieldSpell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1BCounter1.setBackground(new java.awt.Color(0, 0, 0));
        p1BCounter1.setText("0");
        p1BCounter1.setBounds(jPanel1.getHeight()/2,jPanel1.getWidth()/2, 30, 25);
        //      p1BCounter1.setBorder(new RoundedBorder(10)); //10 is the radius
        p1BCounter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1BCounter1MouseClicked(evt);
            }
        });

        p1LP.setEditable(false);
        p1LP.setForeground(new java.awt.Color(0, 0, 255));
        p1LP.setText("4000");
        lifePoints.add(p1LP);
        p1LP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p1LPKeyPressed(evt);
            }
        });

        p2Graveyard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p2FieldSpell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Monster10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N
        p1Monster10.setBorderPainted(false);

        p2Extra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1Spell10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N
        p1Spell10.setBorderPainted(false);

        p2Deck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-ZX-Site.png"))); // NOI18N

        p1LPa.setText("jButton1");
        p1LPa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p1LPaMouseReleased(evt);
            }
        });

        p1LPs.setBackground(new java.awt.Color(255, 255, 255));
        p1LPs.setText("-");
        p1LPs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p1LPsMouseReleased(evt);
            }
        });

        p2LPa.setText("jButton1");
        p2LPa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p2LPaMouseReleased(evt);
            }
        });

        p2LPs.setBackground(new java.awt.Color(255, 255, 255));
        p2LPs.setText("-");
        p2LPs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p2LPsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p2Extra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p2Deck, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p1Deck, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Spell5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Extra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p1Graveyard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Monster1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Monster2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Monster3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Monster4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1Monster5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(p1FieldSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p2FieldSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(p1Monster10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(p1Monster9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(p1Monster8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(p1Monster7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(p1Monster6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(p2Graveyard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p2LP, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1LPa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1LPs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132)
                        .addComponent(p1BCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p2LPa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2LPs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p1LP, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(filler7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(230, 230, 230))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(p1Deck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Spell1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Spell2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Spell3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Spell4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Spell5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(p1Extra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(p1Graveyard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(p1Monster1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Monster2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Monster3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Monster4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(p1Monster5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(p1FieldSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p1BCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1LP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(p1LPa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p1LPs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(p2LPa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p2LPs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(p2LP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2Graveyard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p1Monster10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Monster9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Monster8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Monster7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Monster6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p2FieldSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2Deck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p1Spell10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Spell9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Spell8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Spell7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Spell6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p2Extra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        p2LP.getAccessibleContext().setAccessibleName("p1LP");
        p2LP.getAccessibleContext().setAccessibleDescription("");
        p1BCounter1.getAccessibleContext().setAccessibleName("Counter1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void p1BCounter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1BCounter1MouseClicked
        // numbers are off by one i.e. counter 1 refers to index 0 may fix in future but we'll see
        temp=++p1BCounters[0];
        p1BCounter1.setText(temp+"");
    }//GEN-LAST:event_p1BCounter1MouseClicked

    private void p1LPaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LPaMouseReleased
        // TODO add your handling code here:
        if(p1LPa.isEnabled())
            setLPFocus(0);
    }//GEN-LAST:event_p1LPaMouseReleased

    private void p1LPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1LPKeyPressed
        // TODO add your handling code here:
        //enter is "10"
        
        if(p1LP.isEditable())
            if(evt.getKeyCode()==10)
                this.lPArithmatic();
    }//GEN-LAST:event_p1LPKeyPressed

    private void p2LPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p2LPKeyPressed
        // TODO add your handling code here:
        //enter is "10"
        if(p2LP.isEditable())
            if(evt.getKeyCode()==10)
                this.lPArithmatic();
    }//GEN-LAST:event_p2LPKeyPressed

    private void p1LPsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LPsMouseReleased
        // TODO add your handling code here:
        
        if(p1LPs.isEnabled())
            setLPFocus(1);
        System.out.println("hey");
    }//GEN-LAST:event_p1LPsMouseReleased

    private void p2LPaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LPaMouseReleased
        // TODO add your handling code here:
        if(p2LPa.isEnabled())
            setLPFocus(2);
        System.out.println("hey");
    }//GEN-LAST:event_p2LPaMouseReleased

    private void p2LPsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LPsMouseReleased
        // TODO add your handling code here:
        
        if(p2LPs.isEnabled())
            setLPFocus(3);
        System.out.println("hey");
    }//GEN-LAST:event_p2LPsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YuGiOhBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YuGiOhBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YuGiOhBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YuGiOhBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new YuGiOhBoard().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(YuGiOhBoard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public YuGiOhBoard(String initLP)
    {
    if(initLP.equalsIgnoreCase("high"))    
          temp=HIGH_LP;
    else
          temp = LOW_LP;
    }
    
    public void myInit()
    {
        for (int i=0;i<lifePoints.size();i++)
        {
            lifePoints.get(i).setText(temp+"");
        }
        
        for(int i=0;i<10;i++)
        {
            p1BCounters[i]=0;
            p2BCounters[i]=0;
            p1RCounters[i]=0;
            p2RCounters[i]=0;
        }
        
        for(int i=0;i<lPMods.length;i++)
        {
           lPMods[i]=false;
        }
    }
    
    private void setLPFocus(int index)
    {
        int lastIndex=-1;
        boolean sameButton=false;
        whichLP=index/2;
        for(int i=0;i<lPMods.length;i++)
        {
           if(lPMods[i]==true)
           {
               lifePoints.get(i/2).setText(prevLPVal);
               lifePoints.get(i/2).setEditable(false);
               lifePoints.get(i/2).requestFocus();
            
               if(i==index)
                    sameButton=true;
                lPMods[i]=false;
            break;
           }
            System.out.println(whichLP+" "+i+" "+index+" "+sameButton);
        }
             if(!sameButton)
             {
               prevLPVal=lifePoints.get(whichLP).getText();
                   prevLPVal=lifePoints.get(whichLP).getText();
                   if(index%2==0)
                    lifePoints.get(whichLP).setText("+");
                   else
                    lifePoints.get(whichLP).setText("-");
                   lifePoints.get(whichLP).setEditable(true);
               
               
            }
    }
    
    private void lPArithmatic()
    {
        if(lifePoints.get(whichLP).isEditable())
        {
            
        int newValue=0;
        String eqn=lifePoints.get(whichLP).getText();
        
        System.out.println(eqn);
        
        
        int startIndex=-1;
        
        String allNumbers="0123456789";
        for(int i=0;i<eqn.length();i++)
        {
            if(allNumbers.indexOf(eqn.charAt(i))>-1)
            {
                startIndex=i;
                break;
            }
            
        }
        
//        System.out.println("entered");
            
        try
        {
           newValue = Integer.parseInt(eqn.substring(startIndex));
        }
        catch(NumberFormatException e)
        {
            lifePoints.get(whichLP).setText("Invalid operation please retry");
        }
            
        if(eqn.equals("")||startIndex==-1)
        {
            lifePoints.get(whichLP).setText(prevLPVal);
            System.out.println(prevLPVal);
            lifePoints.get(whichLP).setEditable(false);
            System.out.println("nope");
        }
        else if(eqn.charAt(0)=='+')
        {
            lifePoints.get(whichLP).setText((newValue+Integer.parseInt(prevLPVal))+"");
            System.out.println((newValue+Integer.parseInt(prevLPVal))+"");
            lifePoints.get(whichLP).setEditable(false);
        }
        else if(eqn.charAt(0)=='-')
        {
            if(newValue<Integer.parseInt(prevLPVal))
                lifePoints.get(whichLP).setText((Integer.parseInt(prevLPVal)-newValue)+"");
            else
            {
                gameOver(whichLP);
            }
            System.out.println((newValue+Integer.parseInt(prevLPVal))+"");
            lifePoints.get(whichLP).setEditable(false);
        }
        else
            lifePoints.get(whichLP).setText("Invalid operation please retry");
        }
    }
    
        private void gameOver(int player)
        {
            for (int i=0;i<lifePoints.size();i++)
                if(whichLP==i)
                    lifePoints.get(whichLP).setText("You Lose");
                else
                    lifePoints.get(i).setText("You Win");
            p1LPa.setEnabled(false);
            p1LPs.setEnabled(false);
            p2LPa.setEnabled(false);
            p2LPs.setEnabled(false);
            
        }
        
        
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton p1BCounter1;
    private javax.swing.JButton p1Deck;
    private javax.swing.JButton p1Extra;
    private javax.swing.JButton p1FieldSpell;
    private javax.swing.JButton p1Graveyard;
    private javax.swing.JTextField p1LP;
    private javax.swing.JButton p1LPa;
    private javax.swing.JButton p1LPs;
    private javax.swing.JButton p1Monster1;
    private javax.swing.JButton p1Monster10;
    private javax.swing.JButton p1Monster2;
    private javax.swing.JButton p1Monster3;
    private javax.swing.JButton p1Monster4;
    private javax.swing.JButton p1Monster5;
    private javax.swing.JButton p1Monster6;
    private javax.swing.JButton p1Monster7;
    private javax.swing.JButton p1Monster8;
    private javax.swing.JButton p1Monster9;
    private javax.swing.JButton p1Spell1;
    private javax.swing.JButton p1Spell10;
    private javax.swing.JButton p1Spell2;
    private javax.swing.JButton p1Spell3;
    private javax.swing.JButton p1Spell4;
    private javax.swing.JButton p1Spell5;
    private javax.swing.JButton p1Spell6;
    private javax.swing.JButton p1Spell7;
    private javax.swing.JButton p1Spell8;
    private javax.swing.JButton p1Spell9;
    private javax.swing.JButton p2Deck;
    private javax.swing.JButton p2Extra;
    private javax.swing.JButton p2FieldSpell;
    private javax.swing.JButton p2Graveyard;
    private javax.swing.JTextField p2LP;
    private javax.swing.JButton p2LPa;
    private javax.swing.JButton p2LPs;
    // End of variables declaration//GEN-END:variables
}